### ISSUE TITLE
Syncing repository URL

### ISSUE THREAD

**Issue by alexewerlof** [danlevan/gulp-config-sync#4]
Package.json: https://docs.npmjs.com/files/package.json#repository

In Bower: https://github.com/bower/bower.json-spec#repository

Quite similar. Would be great to sync this by default. Thanks for the great plugin. We use it daily.

**Comment by 8lueberry** [comment]
Great idea :) I'll make that change.

**Comment by 8lueberry** [comment]
v1.0.1
- Sync 'repository' by default
