### ISSUE TITLE
Can you add an "onlyFields" option?

### ISSUE THREAD

**Issue by alexewerlof** [danlevan/gulp-config-sync#6]
Hi,
Thanks for this awesome plugin. I am a Chrome extension developer and I use this plugin go automatically generate the contents of my manifest.json from package.json.

Chrome is very strict about what can be in manifest.json and doesn't allow the "license" and "repository" field.

I tried explicitly specifying the files like this:

```
.pipe(confSync({
      src: './package.json',
      fields: ['name', 'version', 'description']
    }))
```

But it still syncs the "license" and "repository" fields from package.json to manifest.json.

I was wondering if this is not a bug for the "fields" option, would it be possible to add an option called "onlyFields" that syncs only and only the properties I mention?
# Test

'manifest.json':

```
{
  "name": "",
  "description": "test",
}
```

package.json (same as https://github.com/danlevan/gulp-config-sync/blob/master/package.json)

configuration:

```
.pipe(confSync({
      src: './package.json',
      fields: ['name', 'version']
    }))
```

Resulting manifest.json

```
{
  "name": "gulp-config-sync",
  "version": "1.0.1"
  "description": "test",
}
```

and no other fields come to manifest.json

**Comment by 8lueberry** [comment]
Hi @hanifbbz thanks for the issue. You are right, it uses _.merge that will add all the default even if you don't specify it.

I made a new release v1.0.2 that should fix this. I created a test like you suggested :)

Let me know if it works.

**Comment by 8lueberry** [comment]
More info:

If you use

``` js
.pipe(confSync({
      src: './package.json',
      fields: ['name', 'version']
    }))
```

That should work :)
